#!/bin/bash

# Path to the commit message file
COMMIT_MSG_FILE=$1

# Regular expression for commit message validation
COMMIT_REGEX='^(feat|fix|docs|style|refactor|perf|test|chore|BREAKING CHANGE)(\(.+\))?!?: .+'
BREAKING_CHANGE_FOOTER_REGEX='BREAKING CHANGE: .+'

# Read commit message
commit_message=$(cat $COMMIT_MSG_FILE)

# Check if commit message matches the regex
if ! [[ $commit_message =~ $COMMIT_REGEX ]] || \
   [[ $commit_message =~ $BREAKING_CHANGE_FOOTER_REGEX && ! $commit_message =~ ! ]]; then
    echo "ERROR: Commit message does not follow Conventional Commits format."
    echo "Refer to: https://www.conventionalcommits.org"
    exit 1
fi

exit 0
