#!/bin/bash

echo 'Running clang-format on staged files...'

files=$(git diff --name-only --cached | grep -E "\.(cpp|hpp)$")

if [ -z "$files" ]; then
    echo "No C++ files to format."
    exit 0
fi

clang-format -i -style=file $files

git add -u
