name: C++ CI

on:
  push:
    branches: [main, develop, feature/CI]
  pull_request:
    branches: [main, develop]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential libtool autoconf unzip wget clang
          sudo apt remove --purge --auto-remove cmake
          version=3.27
          build=7
          mkdir ~/temp
          cd ~/temp
          wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
          tar -xzvf cmake-$version.$build.tar.gz
          cd cmake-$version.$build/
          ./bootstrap
          make -j$(nproc)
          sudo make install

      - name: Build with CMake and Clang
        run: |
          mkdir build && cd build
          cmake ..
          make

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          choco install llvm

      - name: Build with CMake and Clang
        run: |
          mkdir build && cd build
          cmake -G "Visual Studio 17 2022" -T ClangCL -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
          cmake --build . --config Release
